# Generated by Django 6.0.1 on 2026-01-21 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('violation_type', models.CharField(choices=[('signal_jump', 'Signal Jump'), ('over_speed', 'Over Speeding'), ('no_helmet', 'No Helmet')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('accident', 'Accident'), ('breakdown', 'Vehicle Breakdown'), ('signal_failure', 'Signal Failure')], max_length=50)),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
